version: '2'
services:
    web:
        build: .
        ports:
           - "5000:5000"
        environment:
           REDIS_HOST: redis
           PYTHONUNBUFFERED: 1
           API_USER_PASSWORD: ${API_USER_PASSWORD}

        volumes:
           - .:/code
        depends_on:
           - redis
        command: python app.py
    redis:
        image: redislabs/redisearch:latest
        command: --port 6380
        ports:
            - "6380:6380"
