version: '2'
services:
    web:
        build: .
        ports:
           - "5000:5000"
        environment:
           REDIS_HOST: redis
           PYTHONUNBUFFERED: 1
        volumes:
           - .:/code
        depends_on:
           - redis
        command: python app.py
    redis:
        image: redislabs/redisearch:latest