version: '2'
services:
    web:
        build: .
        ports:
           - "5000:5000"
        environment:
           REDIS_HOST: redisearch
           PYTHONUNBUFFERED: 1
           API_USER_PASSWORD: ${API_USER_PASSWORD}

        volumes:
           - .:/code
        depends_on:
           - redisearch
        command: python app.py
    redisearch:
        image: redislabs/redisearch:latest
        ports:
            - "6380:6380"
