from bs4 import BeautifulSoup


def get_title_content(html_content) -> dict:
    """Gets a partial html document generated by GitHub from a markdown files
    and returns a dictionary with the titles included in the html with the
    contents below them until a new title is found.

    Parameters
    ----------
    html_content : str
        The html file

    Returns
    -------
    dict
        A dict with title anchor strings as keys and a list of the text found in each
        element below them.
    """

    soup = BeautifulSoup(html_content, 'html.parser')

    titles = [link for link in soup.find_all('a') if link.get('href') and link.get('href')[0] == "#"]
    title_content = {}

    for i, current_element in enumerate(titles):
        # Links are inside a header element, we move from header to header
        header = current_element.parent
        href = header.a.get('href')
        title_content[href] = []
        if i < len(titles)-1:
            while header != titles[i+1].parent:
                if hasattr(header, 'get_text') and header.get_text():
                    title_content[href].append(header.get_text())
                header = header.next_sibling
        else:
            while header.next_sibling:
                if hasattr(header, 'get_text') and header.get_text():
                    title_content[href].append(header.get_text())
                header = header.next_sibling

    return title_content
